name: "go-chaos build dev"
on: 
  push:
    branches-ignore: 
      - main
    
jobs:
  build-dev:
    runs-ons: ubuntu-latest
    steps: 
      - name: "setup-go"
        uses: actions/setup-go@v3
          with:
            go-version: '^1.18'
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Run build dev"
        run: go build -o go-chaos .
        shell: bash