name: "go-chaos release"
on: 
  push:

    
jobs:
  build-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, freebsd, darwin]
        goarch: [amd64, arm64]
    steps: 
      - name: "setup-go"
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: "Checkout code"
        uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "go-chaos"
      